### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by alpoi-old** [alpoi/BigweldJS#1]
# Important
## Bot
- [x] Login with token
- [x] Bot info UI
- [x] In-app console
- [ ] Pop-out console
- [x] Invalid token handling
- [ ] No internet handling
- [ ] Discord down handling
- [ ] Create invite link with scopes

## Guilds
- [x] Fetch guilds from API
- [x] Guild UI
- [x] Generate guild list
- [x] Refresh guild list
- [ ] Fetch guild members
- [x] Leave guild
- [ ] Leave guild confirmation prompt
- [ ] List of available commands
- [ ] Display banner
- [ ] Display emotes
- [ ] Display nitro boosts

## Commands
- [ ] Command UI 
- [ ] Generate command list from files
- [ ] Display command source code
- [ ] Syntax highlighting (prism, highlight, tree-sitter)
- [ ] Command renewal (manual or automatic)
- [ ] Command toggle
- [ ] Unsaved changes indicator
- [ ] Trusted code disclaimer
- [ ] Register commands per-guild, per-user

## Embeds
- [ ] Embed UI
- [ ] Dynamically display embed during creation
- [ ] Embed saving/loading
- [ ] Send embed to Channel in Guild or DM with User

# In future
- [ ] Interactions https://discord.js.org/#/docs/discord.js/stable/class/Interaction
- [ ] Shards and large server handling
- [ ] Moderation tools
- [ ] Music playback
- [ ] Soundboard playback
- [ ] Trusted command repository
